// <auto-generated />
using System;
using DocIntel.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DocIntel.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260423135348_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("DocIntel.Domain.Entities.DocIntelDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("DocIntelDocuments");
                });

            modelBuilder.Entity("DocIntel.Domain.Entities.DocumentTag", b =>
                {
                    b.Property<Guid>("DocIntelDocumentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("DocIntelDocumentId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("DocumentTags");
                });

            modelBuilder.Entity("DocIntel.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("DocIntel.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DocIntelDocumentTag", b =>
                {
                    b.Property<Guid>("DocIntelDocumentsId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("TEXT");

                    b.HasKey("DocIntelDocumentsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("DocIntelDocumentTag");
                });

            modelBuilder.Entity("DocIntel.Domain.Entities.DocIntelDocument", b =>
                {
                    b.HasOne("DocIntel.Domain.Entities.User", "User")
                        .WithMany("DocIntelDocuments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("DocIntel.Domain.ValueObjects.FileName", "FileName", b1 =>
                        {
                            b1.Property<Guid>("DocIntelDocumentId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("TEXT")
                                .HasColumnName("FileName");

                            b1.HasKey("DocIntelDocumentId");

                            b1.ToTable("DocIntelDocuments");

                            b1.WithOwner()
                                .HasForeignKey("DocIntelDocumentId");
                        });

                    b.Navigation("FileName")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DocIntel.Domain.Entities.DocumentTag", b =>
                {
                    b.HasOne("DocIntel.Domain.Entities.DocIntelDocument", "DocIntelDocument")
                        .WithMany("DocumentTags")
                        .HasForeignKey("DocIntelDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocIntel.Domain.Entities.Tag", "Tag")
                        .WithMany("DocumentTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocIntelDocument");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("DocIntel.Domain.Entities.User", b =>
                {
                    b.OwnsOne("DocIntel.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("EmailAddress")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("TEXT")
                                .HasColumnName("Email");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();
                });

            modelBuilder.Entity("DocIntelDocumentTag", b =>
                {
                    b.HasOne("DocIntel.Domain.Entities.DocIntelDocument", null)
                        .WithMany()
                        .HasForeignKey("DocIntelDocumentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocIntel.Domain.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DocIntel.Domain.Entities.DocIntelDocument", b =>
                {
                    b.Navigation("DocumentTags");
                });

            modelBuilder.Entity("DocIntel.Domain.Entities.Tag", b =>
                {
                    b.Navigation("DocumentTags");
                });

            modelBuilder.Entity("DocIntel.Domain.Entities.User", b =>
                {
                    b.Navigation("DocIntelDocuments");
                });
#pragma warning restore 612, 618
        }
    }
}
